export { default as LoginScreen } from './auth/Loginscreen';
export { default as SignupScreen } from './auth/SignupScreen';
export { default as RegisterYourCompaney } from './auth/RegisterYourCompaney';
export { default as HomeScreen } from './deshboard/HomeScreen';
export { default as Menuscreen } from './deshboard/MenuScreen';
export { default as YourLocation } from './deshboard/YourLocation';
export { default as Serchingscreens } from './deshboard/Serchingscreens';
export { default as Compananees } from './deshboard/Compananees';
export { default as UserProfile } from './deshboard/UserProfile';
export { default as ContectUs } from './deshboard/Userinfoscreen/ContectUs';
export { default as Profile } from './deshboard/Userinfoscreen/Profile';
export { default as MyOrder } from './deshboard/Userinfoscreen/MyOrder';
export { default as PreviewOrder } from './deshboard/Userinfoscreen/MyOreder/PreviewOrder';
export { default as Serials } from './deshboard/console/ConsoleForm/Products/Serials';
export { default as PdfePreviewDownload } from './deshboard/Userinfoscreen/MyOreder/PdfePreviewDownload';
export { default as Console } from './deshboard/Userinfoscreen/Console';
export { default as MyCoupens } from './deshboard/Userinfoscreen/MyCoupens';
export { default as MyAdrress } from './deshboard/Userinfoscreen/MyAdrress';
export { default as HelpandSupport } from './deshboard/Userinfoscreen/HelpandSupport';
export { default as ProductlistPage } from './deshboard/ProductlistPage';
export { default as CartScreen } from './deshboard/CartScreen';
export { default as Screenshot } from './deshboard/screenshot/Screenshot';
export { default as PaymentOption } from './deshboard/PaymentOption/PaymentOption';
export { default as Order } from './deshboard/console/Order';
export { default as Brands } from './deshboard/console/Brands';
export { default as PickOrder } from './deshboard/console/PickOrder';
export { default as PackOrder } from './deshboard/console/PackOrder';
export { default as Dispatch } from './deshboard/console/Dispatch';
export { default as Users } from './deshboard/console/Users';
export { default as Products } from './deshboard/console/Products';
export { default as ProductCategories } from './deshboard/console/ProductCategories';
export { default as ProductVarient } from './deshboard/console/ProductVarient';
export { default as EcommerceCategries } from './deshboard/console/EcommerceCategries';
export { default as PriceList} from './deshboard/console/PriceList';
export { default as ProductsTransfer} from './deshboard/console/ProductsTransfer';
export { default as ProductDataUpdate} from './deshboard/console/ProductDataUpdate';
export { default as StockInventory} from './deshboard/console/StockInventory';
export { default as Dashboard} from './deshboard/console/Dashboard';
export { default as Promotion} from './deshboard/console/Promotion';
export { default as Brand} from './deshboard/console/Brand';
export { default as Uom} from './deshboard/console/Uom';
export { default as BillingAddress} from './deshboard/BillingAddress';
export { default as ConfirmOrder} from './deshboard/ConfirmOrder';
// Form Start =========

export { default as CreateOrder} from './deshboard/console/ConsoleForm/Order/CreateOrder';
export { default as Editorder} from './deshboard/console/ConsoleForm/Order/Editorder';
export { default as Invoice} from './deshboard/console/ConsoleForm/Order/Invoice';
export { default as Delivery} from './deshboard/console/ConsoleForm/Order/Delivery';


// 
export { default as PreviewPick} from './deshboard/console/ConsoleForm/Pick/PreviewPick';
export { default as Packpreview} from './deshboard/console/ConsoleForm/Pack/Packpreview';
export { default as Dispatchpreview} from './deshboard/console/ConsoleForm/Dispatch/Dispatchpreview';
export { default as ProductsPreview} from './deshboard/console/ConsoleForm/Products/ProductsPreview';
export { default as CreateProducts} from './deshboard/console/ConsoleForm/Products/CreateProducts';
export { default as ProductEdit} from './deshboard/console/ConsoleForm/Products/ProductEdit';
export { default as Varientprod} from './deshboard/console/ConsoleForm/Products/Varientprod';
export { default as Productattribute} from './deshboard/console/ConsoleForm/Products/Productattribute';
export { default as UpdateQuentity} from './deshboard/console/ConsoleForm/Products/UpdateQuentity';
export { default as EditproductVarients} from './deshboard/console/ConsoleForm/productsvarients/EditproductVarients';
export { default as CreatePriceList} from './deshboard/console/ConsoleForm/Pricelist/CreatePriceList';
export { default as EditPriceList} from './deshboard/console/ConsoleForm/Pricelist/EditPriceList';

export { default as CreateUserConsole} from './deshboard/console/ConsoleForm/User/CreateUserConsole';
export { default as EditConsoleUser} from './deshboard/console/ConsoleForm/User/EditConsoleUser';
export { default as CreatePromotion} from './deshboard/console/ConsoleForm/Promotion/CreatePromotion';
export { default as UpdatePromotion} from './deshboard/console/ConsoleForm/Promotion/UpdatePromotion';
export { default as AttributePreview} from './deshboard/console/ConsoleForm/Products/AttributePreview';
export { default as Success} from './deshboard/Success';
export { default as PayUWebView} from '../constant/PayUWebView';
export { default as PreviewQtyUpdate} from '../screens/deshboard/console/ConsoleForm/Order/PreviewQtyUpdate';
export { default as CaompareProduct} from '../screens/deshboard/Userinfoscreen/ProductOrderPreview/CaompareProduct';
export { default as PreviewProductorder} from '../screens/deshboard/Userinfoscreen/ProductOrderPreview/PreviewProductorder';
export { default as PreviewconsoleDelivery} from '../screens/deshboard/console/ConsoleForm/Order/PreviewconsoleDelivery';
export { default as PreviewVarientprod} from '../screens/deshboard/console/ConsoleForm/Products/PreviewVarientprod';
export { default as RenewMembership} from '../screens/deshboard/console/ConsoleForm/Deshboard/RenewMembership';
export { default as PreviewProductsComo} from '../components/Productscompo/PreviewProductsComo';
// export { default as StockInventory} from './deshboard/console/StockInventory';
// export { default as Uom} from './deshboard/console/Uom';
