



// Base URL
// export const BASE_URL = 'https://shopaas.arkess.com';
export const BASE_URL = 'http://192.168.31.93:8000';

export const API_URLS = {
  login: BASE_URL + '/login',
  sign_up: BASE_URL + '/customer_signup',
  customerSignup: BASE_URL + '/customer_signup',
  country_list: BASE_URL + '/get_country_list',
  getSliders: BASE_URL + '/fetch_sliders',
  getcatagory: BASE_URL + '/homepage',
  getLocation: BASE_URL + '/find_live_location_data',
  confirmLocation: BASE_URL + '/set_location_session_data',
  getCompanies: BASE_URL + '/companies',
  getSessionInfo: BASE_URL + '/session_info',
  getOtp: BASE_URL + '/send_otp',
  resetPassword: BASE_URL + '/reset_password',
  getAddresses: BASE_URL + '/get_address',
  logout: BASE_URL + '/session_logout',
  getCompanyInfo: BASE_URL + '/get_company_info',
  getProducts: BASE_URL + '/products',
  AddFavourate: BASE_URL + '/my_favourite',
  searchProduct: BASE_URL + '/search_product',
  getCart: BASE_URL + '/get_cart',
  addToCart: BASE_URL + '/add_to_cart',
  resetCart: BASE_URL + '/reset_cart',
  checkCart: BASE_URL + '/check_cart',
  getGeoData: BASE_URL + '/getGeoData',
  redeemRewardPoints: BASE_URL + '/redeem_reward_points',
  addDelivery: BASE_URL + '/delivery_process',
  getStoreOrders: BASE_URL + '/store/orders',
  getStoreOrderData: BASE_URL + '/store/order_data',
  saveStoreOrderData: BASE_URL + '/store/save_order_data',
  getOrderDeliveryData: BASE_URL + '/store/order/delivery_data',
  saveOrderDeliveryData: BASE_URL + '/store/order/save_delivery_data',
  getOrderInvoiceData: BASE_URL + '/store/order/invoice_data',
  saveOrderInvoiceData: BASE_URL + '/store/order/save_invoice_data',
  storeBrands: BASE_URL + '/store/brands',
  saveStoreBrand: BASE_URL + '/store/save_brand',
  storeUomCategory: BASE_URL + '/store/uom_category',
  saveUomCategory: BASE_URL + '/store/save_uom_category',

  getUserCoupons: BASE_URL + '/endConsumer/coupons',
  applyPromo: BASE_URL + '/apply_coupon',
  getFAQS: BASE_URL + '/product_faq',
  getLEGALS: BASE_URL + '/product_legal',

  extension: '/shopaas',
  googleLogin: BASE_URL + '/Google_login',
  authlogin: BASE_URL + '/authlogin',
  getProductDetails: BASE_URL + '/product_details',
  processCheckout: BASE_URL + '/process_checkout',
  putAdress: BASE_URL + '/add_address',
  selectShippingAddress: BASE_URL + '/select_shipping_address',
  getPaymentDetails: BASE_URL + '/payment_details',
  payNow: BASE_URL + '/pay_now',
  getPaymentConfirmationData: BASE_URL + '/payment_confirmation',
  getUserOrders: BASE_URL + '/endConsumer/orders',
  sendFeedback: BASE_URL + '/order/review_rating',
  cancelOrder: BASE_URL + '/order/cancel',
  reOrder: BASE_URL + '/order/re-order',
  orderDetails: BASE_URL + '/order/details',
  relatedProducts: BASE_URL + '/related_products',
  searchCompany: BASE_URL + '/search_company',
  compareProduct: BASE_URL + '/compare_product',
  company_types: BASE_URL + '/get_sub_company_types',
  getReturnCart: BASE_URL + '/get_return_cart',
  processReturnOrder: BASE_URL + '/return_order',
  registerCompany: BASE_URL + '/register_your_company',

  redeemPoints: BASE_URL + '/redeemPoints',
  companyDataTransfer: BASE_URL + '/company/products/data_transfer',
  saveCompanyDataTransfer: BASE_URL + '/company/products/save_data_transfer',
  getProductOptions: BASE_URL + '/company/products/options',
  productDataUpdate: BASE_URL + '/company/products/product_data_update',
  saveProductDataUpdate: BASE_URL + '/company/products/save_product_data',
  stockInventory: BASE_URL + '/company/stock_inventory',
  saveStockInventory: BASE_URL + '/company/save_stock_inventory',

  getUserData: BASE_URL + '/users',
  saveUserData: BASE_URL + '/users',
  getUsersTreeData: BASE_URL + '/users_tree_data',

  storeProducts: BASE_URL + '/store/products',
  storeCategories: BASE_URL + '/store/categories',
  saveStoreCategory: BASE_URL + '/store/save_category',
  storeProductVarientTree: BASE_URL + '/store/productVarients',
  saveStoreProductsVarient: BASE_URL + '/store/save_variant_product',
  saveStoreProducts: BASE_URL + '/store/save_product',
  renewMembership: BASE_URL + '/store/renew_membership',
  pricelists: BASE_URL + '/store/pricelists',
  savePricelist: BASE_URL + '/store/save_pricelist',

  saveLoyaltyData: BASE_URL + '/save_loyalty',
  getLoyaltyData: BASE_URL + '/get_loyalty',
  savePromtionData: BASE_URL + '/save_promotion_program',
  getPromotionData: BASE_URL + '/promotion_program',
  getSpecificData: BASE_URL + '/get_specific_data',
  dashboardOrdersData: BASE_URL + '/dashboard/ordersData',
  languages: BASE_URL + '/languages',
  getToCompanyData: BASE_URL + '/company/products/get_to_field_data',

  UpdateQty: BASE_URL + '/UpdateQuantity',
  SaveUpdateQty: BASE_URL + '/SaveUpdateQuantity',

  getVariantData: BASE_URL + '/get_VariantData',
  LotSerialTree: BASE_URL + '/lot_serial_tree',
  prodcutLot: BASE_URL + '/product_lot',
  saveProdcutLot: BASE_URL + '/save_product_lot',

  ProductAttributeTree: BASE_URL + '/ProductAttributeTreeData',
  ProductAttributeForm: BASE_URL + '/ProductAttributeFormData',
  SaveProductAttribute: BASE_URL + '/SaveProductAttributeData',

  toggleCompanyUser: BASE_URL + '/internal_user/convert_user',
  getContactUsData: BASE_URL + '/contactUsData',
  SavecontactUS:BASE_URL+'/contactus_data',
  customerOrderDetails: BASE_URL + '/endConsumer/orderDetails',

  changeActivePriceList1: BASE_URL + '/store/changeActivePriceList1',
  razorpay_api: BASE_URL + '/payment/razorpay/capture',
  validateDelivery: BASE_URL + '/validate_delivery',
  shortClose: BASE_URL + '/order/short_close',

  fetch_stock_picking_pick:BASE_URL+'/api/fetch_stock_picking_pick',
  fetch_stock_picking_pack:BASE_URL+'/api/fetch_stock_picking_pack',
  fetch_stock_picking_dispatch:BASE_URL+'/api/fetch_stock_picking_dispatch',
  fetchcreate_order:BASE_URL+'/createOrder',
  fetchTaxesDetails:BASE_URL+'/TaxesDetails',
  SavefetchDetails:BASE_URL+'/api/taxes_details'
 
};
