export default {
  INITIALSCREEN: 'initialScreen',
  LOGIN: 'login',
  SIGNUP: 'signup',
  HOMESCREEN: 'homescreen',
  MENUSCREEN: 'menuscreen',
  LOCATION: 'Location',
  SEACRHINGSCREEN: 'Serchingscreens',
  COMPANESS: 'companess',
  USERPROFILES: 'UserProfile',
  TABROUTE: 'Tabroute',
  PROFILE: 'Profile',
  MYORDER: 'MyOrder',
  MYCOUPEN: 'MyCoupens',
  MYADDRESS: 'MyAddress',
  PRODUCTSCREEN: 'ProductlistPage',
  CARTSCREEN: 'CartScreen',
  SCREENSHOT: 'ScreenShot',
  PAYMENTOPTION: 'PaymentOption',
  CONSOLE: 'Console',
  ORDER: 'Order',
  COMPANEYBRAND: 'Brands',
  HELPANDSUPPORT: 'Help And Support',
  PICKORDER: 'PickOrder',
  PACKORDER: 'PackOrder',
  USERS: 'Users',
  DISPATCH: 'Dispatch',
  PRODUCTS: 'Products',
  PRODUCTCATEGORIES: 'ProductCategories',
  PRODUCTVARIENT: 'ProductVariants',
  PRODUCTCATEGORY: 'ProductCategories',
  ECOMMERCECATEGORIES: 'EcommerceCategories',
  PRICELISTS: 'PriceLists',
  PRODUCTTRANSFER: 'ProductTransfer',
  PRODUCTDATAUPDATE: 'ProductDataUpdate',
  STOCKINVENTORY: 'Stock Inventory',
  DASHBOARD: 'Dashboard',
  PROMOTION: 'Promotion',
  LOYALITY: 'Loyality',
  BRAND: 'Brand',
  UOM: 'Uom',
  CREATEORDER: 'CreateOrder',
  EDITORDER: 'Edit Order',
  INVOICE: 'Invoice',
  DELIVERY: 'Delivery',
  PREVIEWPICK: 'PreviewPick',
  PACKPREVIEW: 'Packpreview',
  DISPATCHPREVIEW: 'Dispatchpreview',
  PRODUCTS_PREVIEW: 'ProductsPreview',
  CREATE_PRODUCTS: 'CreateProducts',
  VARIENTPROD: 'Varientprod',
  PRODUCTATTRIBUTE: 'Productattribute',
  UPDATEQUENTITY: 'UpdateQuentity',
  EDITPTODUCTVARIENTS: 'EditproductVarients',
  CREATEPRICELIST: 'CreatePriceList',
  EDITPRICELIST:'EditPriceList',
  CREATEUSERCONSOLE: 'CreateUserConsole',
  EDITUSERCONSOLE: 'EditConsoleUser',
  CREATEPROMOTION: 'CreatePromotion',
  UPDATEPROMOTION: 'UpdatePromotion',
  BILLINGADDRESS:'BillingAddress',
  CONFIRMORDER:'ConfirmOrder',
  ATTRIBUTEPREVIEW:'AttributePreview',
  SUCCESS:"Success",
  PRODUCTSEDIT:'ProductEdit',
  REGISTERYOURCOMPANEY:'RegisterYourCompaney',
  PREVIEVORDER:'PreviewOrder',
  PDFPREVIEWDOWNLOAD:'PdfePreviewDownload',
  SERIALS:'Serials',
  PAYUWEBVIEW:'PayUWebView',
  PREVIEWQTYUPDATE:'PreviewQtyUpdate',
  COMPAREPRODUCT:'CaompareProduct',
  PREVIEWPRODUCTORDER:'PreviewProductorder',
  PREVIEWCONSOLEDELIVERY:'PreviewconsoleDelivery',
  PREVIEWVARIENTPROD:'PreviewVarientprod',
  CONTECTUS:'ContectUs',
  RENEWMEMBERSHIP:'RenewMembership',
  PREVIEWPRODUCTSCOMPO:'PreviewProductsComo',
};
